### PR TITLE
Update SUNDIALS API in condense solver. Closes #33

### LINKED ISSUE #33: Update SUNDIALS support to version 2.6

### PR DESCRIPTION
**Pull request by slayoo**
Just a first try at solving the SUNDIALS API problem.

Seems to work locally with SUNDIALS 5.8.0 (i.e. the test_condense passes and it does so much quicker that without supplying the preconditioner).

We can try to retain compatibility with the old version with some #ifdefs, if needed.

Getting SUNDIALS installed in the docker images and pointing CMake to it is essential, let me ask for your input here.

HTH,
Sylwester

### CODE REVIEW

**Comment by slayoo** [comment]
@mwest1066 success - compilation with condensation support and condense  test run on CI OK:

image

**Comment by jcurtis2** [comment]
I've manually compiled and tested this running Sundials 5.8.0 with all tests passing.

However it looks like with the CAMP merge (#162), we introduced some unnecessary things to the build process in CMakeList.txt like SuiteSparse (and metis to the dockerfile) that went unnoticed as we weren't testing the condensation code at the time. These aren't necessary when turning on SUNDIALS for the condensation code.

I figure it makes as much sense to remove it here (in CMakeList.txt and the Dockerfile) rather than a separate pull request, thoughts?

**Comment by slayoo** [comment]
for the record, yet another change will be needed to make it work with Sundials >= 6.0.0
https://github.com/LLNL/sundials/releases/tag/v6.0.0

**Review by jcurtis2 — APPROVED** [review]
This looks ready to merge to me. Code works with newer versions of sundials (both in the docker as well as with a manually compiled SUNDIALS (v5.8.0)). Also we now test the condensation code in the build process so we will be aware of when the cloud parcel model breaks.

**Pull request merged**
