### PR TITLE
Develop 114 adapt gpu

### PR DESCRIPTION
**Pull request by cguzman95**
Adaptation of calc_deriv and calc_jac are done. Some reactions are not computed on GPU and calculated on CPU after. Unit tests working fine with GPU flag ON. Missing test it with some mechanisms that use the non-implemented reactions (HL, SIMPOL, aqueous and condensed_arrhenius) and other implemented reactions to ensure all the contributions are added correctly.

NOTE: There are a few changes in .f files like camp_core and rxn_data. These changes are only to ensure update_data works by setting updating only the first cell. I encourage to merge also this changes as provisional until we correctly update all cells.

### CODE REVIEW

**Comment by mattldawson** [comment]
one of the recent changes to the update data objects is to allow them to update any cell - i think this is already working in chem_mod (i’ll check tomorrow)

**Comment by cguzman95** [comment]
Nice - I will check it also (and fix the compilation errors caused by forgetting to test DEBUG flag)

**Comment by cguzman95** [comment]
There is a bug with new unit tests GPU - I'm fixing that in #126

**Comment by mattldawson** [comment]
that's cool - do you still want me to merge this?

**Comment by cguzman95** [comment]
Yes, please. And remember to check my big comment on #92 when you can

**Comment by mattldawson** [comment]
ok, I may not get to that for a few days - I need to focus on the MONARCH implementation, but I'll start going through the list as I have time

**Comment by cguzman95** [comment]
Ok, no worries - I will fix the GPU issues on #126 alongside correct testing, and go with documentation and other things, so I have entertainment xD

**Comment by mattldawson** [comment]
@cguzman95 - do you want to keep this branch open after the merge or should I delete it?

**Pull request merged**
